######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 5 23:07:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h MainWindow.h
SOURCES += Dialog.cpp main.cpp MainWindow.cpp
